"""Tests for GapfillActivity.

Gapfill builds re-hunt tasks from REAL gaps only — hunter-reported coverage gaps
and gaps the gapfill agent genuinely finds — deduped by (vuln_class, scope). There
is no synthetic coverage floor: when there are no real gaps, gapfill returns no
tasks (it must not send hunters after every vuln class for nothing).
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel

from quarry.schemas import (
    AgentTask,
    CoverageLedger,
    VulnerabilityClass,
)
from quarry_activities.gapfill import gapfill_impl
from quarry_models.loop import ToolCallRequest
from quarry_models.mock_client import MockModelClient

_NOW = datetime(2026, 6, 9, tzinfo=UTC)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class GapfillResponse(BaseModel):
    """Mock response schema for the gapfill agent loop."""

    gaps: list[dict[str, Any]] = []
    tool_calls: list[ToolCallRequest] = []


def _make_ledger(scan_id: str = "scan-1") -> CoverageLedger:
    return CoverageLedger(
        id="ledger-1",
        scan_id=scan_id,
        workspace_id="ws-1",
        agent_tasks_total=10,
        agent_tasks_scanned=5,
        vuln_classes_requested=[VulnerabilityClass.XSS, VulnerabilityClass.COMMAND_INJECTION],
        vuln_classes_completed=[VulnerabilityClass.XSS],
        created_at=_NOW,
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestGapfillActivityGapIdentified:
    def test_gap_identified_when_agent_reports_one(self) -> None:
        """A gap the gapfill agent reports becomes one re-hunt task for that class."""
        ledger = _make_ledger()
        client = MockModelClient(
            default=GapfillResponse(
                gaps=[
                    {"vuln_class": "command_injection", "scope": "src/", "reason": "sink untraced"}
                ]
            )
        )

        result = gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=[VulnerabilityClass.COMMAND_INJECTION],
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        ci_tasks = [t for t in result if t.vuln_class == VulnerabilityClass.COMMAND_INJECTION]
        assert len(ci_tasks) == 1


class TestGapfillNoFloor:
    def test_no_tasks_when_no_real_gaps(self) -> None:
        """No coverage floor: empty agent output + no hunter gaps → no re-hunt tasks.

        Previously a synthetic floor forced ≥2 re-hunts per class even with nothing
        to find, sending hunters on a wild goose chase. That is gone.
        """
        ledger = _make_ledger()
        client = MockModelClient(default=GapfillResponse(gaps=[]))

        result = gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=[VulnerabilityClass.IDOR],
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        assert result == []

    def test_gapfill_tasks_have_correct_source(self) -> None:
        """Tasks generated by gapfill must have source='gapfill'."""
        ledger = _make_ledger()
        client = MockModelClient(
            default=GapfillResponse(
                gaps=[{"vuln_class": "ssrf", "scope": "src/", "reason": "untraced fetch"}]
            )
        )

        result = gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=[VulnerabilityClass.SSRF],
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        assert result, "expected at least one gap task"
        for task in result:
            assert task.source == "gapfill"


class TestGapfillDeduplication:
    def test_no_duplication_across_hunter_and_agent_gaps(self) -> None:
        """A hunter gap and an agent gap for the same (class, scope) dedup to one task."""
        ledger = _make_ledger()
        # Agent reports a gap for (file_upload, src/); hunter reports the same area.
        client = MockModelClient(
            default=GapfillResponse(
                gaps=[{"vuln_class": "file_upload", "scope": "src/", "reason": "agent gap"}]
            )
        )

        result = gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=[VulnerabilityClass.FILE_UPLOAD],
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
            hunter_gaps=[{"area": "src/", "reason": "hunter gap", "vuln_class": "file_upload"}],
        )

        fu_scoped_tasks = [
            t
            for t in result
            if t.vuln_class == VulnerabilityClass.FILE_UPLOAD and t.scope == "src/"
        ]
        assert len(fu_scoped_tasks) == 1, (
            f"Expected one deduped (file_upload, src/) task, got {len(fu_scoped_tasks)}"
        )


class TestGapfillExistingFindingsContext:
    def test_skips_gap_already_covered_by_existing_finding(self) -> None:
        """A gap for an area an existing finding already covers must NOT become a re-hunt task."""
        ledger = _make_ledger()
        client = MockModelClient(
            default=GapfillResponse(
                gaps=[{"vuln_class": "ssrf", "scope": "src/", "reason": "fetch helper untraced"}]
            )
        )

        result = gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=[VulnerabilityClass.SSRF],
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
            existing_findings=[
                {
                    "vuln_class": "ssrf",
                    "title": "SSRF in fetch",
                    "affected_component": "src/app.py:42",
                }
            ],
        )

        ssrf_tasks = [t for t in result if t.vuln_class == VulnerabilityClass.SSRF]
        assert ssrf_tasks == [], "ssrf in src/ already has a finding — no re-hunt task expected"

    def test_creates_gap_for_uncovered_area_despite_findings(self) -> None:
        """An uncovered (class, scope) still becomes a task even when other findings exist."""
        ledger = _make_ledger()
        client = MockModelClient(
            default=GapfillResponse(
                gaps=[{"vuln_class": "xss", "scope": "routes/", "reason": "templates untraced"}]
            )
        )

        result = gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=[VulnerabilityClass.XSS],
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
            existing_findings=[
                {"vuln_class": "ssrf", "title": "SSRF", "affected_component": "src/app.py:42"}
            ],
        )

        xss_tasks = [
            t for t in result if t.vuln_class == VulnerabilityClass.XSS and t.scope == "routes/"
        ]
        assert len(xss_tasks) == 1


class TestGapfillReturnType:
    def test_returns_list_of_agent_tasks(self) -> None:
        """The gapfill activity must return a list of AgentTask."""
        ledger = _make_ledger()
        focused = [VulnerabilityClass.XSS]
        client = MockModelClient(default=GapfillResponse())

        result = gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=focused,
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        assert isinstance(result, list)
        for item in result:
            assert isinstance(item, AgentTask), f"Expected AgentTask, got {type(item)}"


# ---------------------------------------------------------------------------
# Panel-aware client selection for gapfill_activity (Change 3)
# ---------------------------------------------------------------------------


def test_gapfill_activity_mock_panel_does_not_call_build() -> None:
    """gapfill_activity with provider=mock must not call build_model_client."""
    from unittest.mock import patch

    from quarry.panel_config import RoleConfig
    from quarry.schemas import Provider
    from quarry_activities.gapfill import gapfill_activity

    mock_panel_json = RoleConfig(provider=Provider.MOCK, model="mock-v1", rpm=30).model_dump_json()
    ledger = _make_ledger()

    with patch("quarry_activities.gapfill.build_model_client") as mock_build:
        gapfill_activity(
            ledger.model_dump(mode="json"), [], None, "/tmp/repo", None, mock_panel_json
        )

    mock_build.assert_not_called()


def test_gapfill_activity_litellm_panel_builds_litellm_client() -> None:
    """gapfill_activity with provider=litellm must call build_model_client and pass policy."""
    from unittest.mock import MagicMock, patch

    from quarry.panel_config import RoleConfig
    from quarry.schemas import Provider
    from quarry_activities.gapfill import gapfill_activity
    from quarry_models.types import ProviderPolicy

    litellm_panel_json = RoleConfig(
        provider=Provider.LITELLM,
        model="chutes/moonshotai/Kimi-K2-Instruct",
        rpm=20,
    ).model_dump_json()
    ledger = _make_ledger()

    fake_client = MagicMock()
    received_policies: list[ProviderPolicy] = []

    def _spy_loop(**kwargs: object) -> object:
        p = kwargs.get("provider_policy")
        if isinstance(p, ProviderPolicy):
            received_policies.append(p)
        from quarry.schemas import AgentLoopResult

        return AgentLoopResult(
            final_answer=None,
            steps=[],
            iterations_used=1,
            total_cost=0.0,
            stop_reason="final_answer",
        )

    with (
        patch(
            "quarry_activities.gapfill.build_model_client", return_value=fake_client
        ) as mock_build,
        patch("quarry_activities.gapfill.run_agent_loop", side_effect=_spy_loop),
    ):
        gapfill_activity(
            ledger.model_dump(mode="json"), [], None, "/tmp/repo", None, litellm_panel_json
        )

    mock_build.assert_called_once()
    assert len(received_policies) == 1
    assert received_policies[0].provider == "litellm"
    assert received_policies[0].model == "chutes/moonshotai/Kimi-K2-Instruct"


def test_gapfill_turns_hunter_gaps_into_rehunt_tasks() -> None:
    """Hunter-reported coverage gaps become targeted re-hunt tasks (scope=area)."""
    ledger = _make_ledger()
    client = MockModelClient(default=GapfillResponse(gaps=[]))
    hunter_gaps = [
        {
            "area": "config/",
            "reason": "did not search for hardcoded secrets",
            "vuln_class": "secrets",
        },
    ]

    result = gapfill_impl(
        ledger=ledger,
        existing_tasks=[],
        vuln_classes=[VulnerabilityClass.SECRETS],
        repo_path=".",
        scan_id="scan-1",
        client=client,
        hunter_gaps=hunter_gaps,
    )

    gap_tasks = [t for t in result if t.scope == "config/"]
    assert len(gap_tasks) == 1
    t = gap_tasks[0]
    assert t.vuln_class == VulnerabilityClass.SECRETS
    assert t.source == "gapfill"
    assert "config/" in t.task_prompt
