"""Tests for GapfillActivity (Week 13 / Part 1C).

Written RED first — these fail until gapfill_activity is implemented.

The activity:
1. Calls enforce_coverage_floor to get mandatory synthetic tasks.
2. Calls run_agent_loop with role='gapfill' to find additional gaps from the ledger.
3. Merges synthetic + agent output, deduped by (vuln_class, scope).

Key invariant: the coverage floor must fire even when the model returns no gaps.
This is tested explicitly — the floor is a correctness invariant, not a hint.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

import pytest
from pydantic import BaseModel

from quarry.schemas import (
    AgentTask,
    CoverageLedger,
    GapfillTask,
    VulnerabilityClass,
)
from quarry_activities.gapfill import _gapfill_impl
from quarry_models.loop import ToolCallRequest
from quarry_models.mock_client import MockModelClient

_NOW = datetime(2026, 6, 9, tzinfo=UTC)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class _GapfillResponse(BaseModel):
    """Mock response schema for the gapfill agent loop."""

    gaps: list[dict[str, Any]] = []
    tool_calls: list[ToolCallRequest] = []


def _make_ledger(scan_id: str = "scan-1") -> CoverageLedger:
    return CoverageLedger(
        id="ledger-1",
        scan_id=scan_id,
        workspace_id="ws-1",
        attack_surface_items_total=10,
        attack_surface_items_scanned=5,
        vuln_classes_requested=[VulnerabilityClass.XSS, VulnerabilityClass.COMMAND_INJECTION],
        vuln_classes_completed=[VulnerabilityClass.XSS],
        created_at=_NOW,
    )


def _make_task(vuln_class: VulnerabilityClass, scope: str = "src/", source: str = "recon") -> AgentTask:
    return AgentTask(
        id=f"task-{vuln_class.value}",
        scan_id="scan-1",
        role="hunt",
        task_name=f"hunt-{vuln_class.value}",
        vuln_class=vuln_class,
        scope=scope,
        source=source,  # type: ignore[arg-type]
        status="pending",
        created_at=_NOW,
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestGapfillActivityGapIdentified:
    def test_gap_identified_for_zero_candidate_class(self) -> None:
        """Gapfill activity returns tasks for a focused class with no prior tasks."""
        ledger = _make_ledger()
        existing_tasks: list[AgentTask] = [
            _make_task(VulnerabilityClass.XSS),
            _make_task(VulnerabilityClass.XSS),
        ]
        focused = [VulnerabilityClass.XSS, VulnerabilityClass.COMMAND_INJECTION]
        # COMMAND_INJECTION has 0 tasks → floor adds 2 tasks

        client = MockModelClient(default=_GapfillResponse(gaps=[]))

        result = _gapfill_impl(
            ledger=ledger,
            existing_tasks=existing_tasks,
            vuln_classes=focused,
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        ci_tasks = [t for t in result if t.vuln_class == VulnerabilityClass.COMMAND_INJECTION]
        assert len(ci_tasks) >= 2, (
            f"Expected at least 2 COMMAND_INJECTION gap tasks, got {len(ci_tasks)}"
        )


class TestGapfillFloorInvariant:
    def test_floor_adds_tasks_when_model_returns_empty(self) -> None:
        """The coverage floor fires even when the model outputs no gaps.

        This is the critical invariant: floor is in Python, not the prompt.
        """
        ledger = _make_ledger()
        existing_tasks: list[AgentTask] = []
        focused = [VulnerabilityClass.IDOR]

        # Model returns no gaps
        client = MockModelClient(default=_GapfillResponse(gaps=[]))

        result = _gapfill_impl(
            ledger=ledger,
            existing_tasks=existing_tasks,
            vuln_classes=focused,
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        idor_tasks = [t for t in result if t.vuln_class == VulnerabilityClass.IDOR]
        assert len(idor_tasks) >= 2, (
            f"Floor must add IDOR tasks even when model returns empty; got {len(idor_tasks)}"
        )

    def test_gapfill_tasks_have_correct_source(self) -> None:
        """Tasks generated by gapfill must have source='gapfill'."""
        ledger = _make_ledger()
        existing_tasks: list[AgentTask] = []
        focused = [VulnerabilityClass.SSRF]

        client = MockModelClient(default=_GapfillResponse(gaps=[]))

        result = _gapfill_impl(
            ledger=ledger,
            existing_tasks=existing_tasks,
            vuln_classes=focused,
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        for task in result:
            assert task.source == "gapfill", (
                f"Gapfill task must have source='gapfill', got '{task.source}'"
            )


class TestGapfillDeduplication:
    def test_no_duplication_when_model_echoes_floor_gap(self) -> None:
        """If the model identifies the same gap as the floor, it is not duplicated."""
        ledger = _make_ledger()
        existing_tasks: list[AgentTask] = []
        focused = [VulnerabilityClass.FILE_UPLOAD]

        # Model returns a gap for FILE_UPLOAD in "src/" (same as floor would add)
        client = MockModelClient(
            default=_GapfillResponse(
                gaps=[{"vuln_class": "file_upload", "scope": "src/", "reason": "No tests found"}]
            )
        )

        result = _gapfill_impl(
            ledger=ledger,
            existing_tasks=existing_tasks,
            vuln_classes=focused,
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        fu_scoped_tasks = [
            t for t in result
            if t.vuln_class == VulnerabilityClass.FILE_UPLOAD and t.scope == "src/"
        ]
        # Should not have more than 2 despite model + floor both finding the same gap
        # (the floor pads to min_per_class=2; model result merges in if not already present)
        assert len(fu_scoped_tasks) <= 2, (
            f"Duplicate gapfill tasks detected for (file_upload, src/): {len(fu_scoped_tasks)}"
        )


class TestGapfillReturnType:
    def test_returns_list_of_agent_tasks(self) -> None:
        """The gapfill activity must return a list of AgentTask."""
        ledger = _make_ledger()
        focused = [VulnerabilityClass.XSS]
        client = MockModelClient(default=_GapfillResponse())

        result = _gapfill_impl(
            ledger=ledger,
            existing_tasks=[],
            vuln_classes=focused,
            repo_path="/tmp/repo",
            scan_id="scan-1",
            client=client,
        )

        assert isinstance(result, list)
        for item in result:
            assert isinstance(item, AgentTask), f"Expected AgentTask, got {type(item)}"
